### ISSUE TITLE
F-droid Support

### ISSUE THREAD

**Issue by jatocih821** [SpartanJ/ImgurViewer#1]
Hey, thank you for making such an awesome app. I want to ask whether you are willing to publish your app on [F-droid](https://f-droid.org), a store for only opensource apps.
[This](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) might be helpful.

Thanks and take care :)

**Comment by SpartanJ** [comment]
I'm absolutely willing, I never did it because the process to upload an app into the F-Droid repositories is not simple enough for my taste. I personally use F-droid a lot, so I know it's great. I'll try to start the process soon. I'll keep this issue open until it's done.

**Comment by jatocih821** [comment]
Thank for the quick reply

Sorry for bothering you @izzyondroid but are you willing to help him if you are free enough?

**Comment by IzzySoft** [comment]
As Aristotle stated: from a wrong assumption (here: "free enough") you can deduce everything :rofl:

@SpartanJ I have no idea how to make the process of [opening an RFP](https://gitlab.com/fdroid/rfp/issues) any simpler. But giving a few points:

* if you could attach the signed APK to your `releases/`, I could grab it from there (also for future releases) and add it to [my repo](https://apt.izzysoft.de/fdroid), which would get you started pretty fast.
* if you could establish [Fastlane structures](https://gitlab.com/snippets/1895688) in your repo here and have that tagged, that would speed up processing above mentioned RFP (and even before being tagged, improve your listing in my repo should you decide for the APK-attachment).
* using static values for [`versionName` and `versionCode` in your `build.gradle`](https://github.com/SpartanJ/ImgurViewer/blob/2.1.1/app/build.gradle#L15) would make automated updates possible for F-Droid.

**Comment by jatocih821** [comment]
Thank you for the reply Izzy, love you 😉

**Comment by IzzySoft** [comment]
Feel free to let me know once the APK is there. No need to ping me if the RFP was opened – opening an RFP always pings me, as I am maintainer there :wink:

**Comment by SpartanJ** [comment]
Thank you very much @IzzySoft! I'll open the RFP probably this week. We'll talk there soon!

**Comment by IzzySoft** [comment]
Looking forward to see you there then! If you meanwhile want your app in my repo (processing at fdroidorg can take a little), my offer still stands. Wouldn't be the first app walking that way (let me check: 158 went through already, plus a few who are staying in both for different reasons).

**Comment by SpartanJ** [comment]
Hi @IzzySoft!
A new version has been released, as you said I uploaded the apk into the release tag:
https://github.com/SpartanJ/ImgurViewer/releases/tag/2.1.7
https://github.com/SpartanJ/ImgurViewer/releases/download/2.1.7/imgurviewer-2.1.7.apk

Can we use your repo as you offered in the first place? Is that's the case, can we upload it there?
Thanks!

**Comment by IzzySoft** [comment]
@SpartanJ Great! And: Yes, and: no. Ahem, meaning you cannot upload – I pull. Same for future updates: you just tag and attach the APK, my updater checks all 24h. Should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.ensoft.imgurviewer) in about 9 hours. If you want to link there then and need a badge, [I have one here](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :wink:

**Comment by SpartanJ** [comment]
Thanks, @IzzySoft ! I will not close this issue though. I'm not convinced about using a repository that it's not installed by default in the F-Droid app. I think that kind of defeat the purpose of being in F-Droid, it should be easily discoverable. So that was the part I was saying it's not easy enough. I'll have to investigate. Meanwhile, we can use you repository (that I really appreciate, as your help).

**Comment by IzzySoft** [comment]
Well, though F-Droid is "distributed" and there are many repositories, I agree: the one at f-droid.org is most trusted, so it's a good goal to have your app there. Once you decided to open an RFP, we'll meet again "over there" (I'm one of the maintainers).

**Comment by SpartanJ** [comment]
@IzzySoft thank you very much for your help, I've been busy these days and I totally forgot about this. I see you took care of it, excellent news! =)

**Comment by IzzySoft** [comment]
Gladly done – enjoy! :smiley:

**Comment by SpartanJ** [comment]
@IzzySoft I'm wondering if there's an easy way to change the email that's being exposed in the application listing in F-droid, I started receiving e-mails in my personal e-mail and also a lot of spam since the release of ImgurViewer in the F-droid store. The correct support e-mail for this application is support[at]ensoft.dev.

**Comment by IzzySoft** [comment]
Done: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7131 – should hopefully be fixed with the next index update. Fixed it in my repo already – but now that the app is listed at F-Droid, I'd usually remove it from mine unless requested otherwise. Do you want it to stay?

**Comment by SpartanJ** [comment]
@IzzySoft Thank you again! Yes, remove the app from your repository, I don't see a good reason to keep it.

**Comment by IzzySoft** [comment]
OK, done. Should the need arise: I've kept the metadata, so we can re-establish it easily anytime.

**Comment by SpartanJ** [comment]
@IzzySoft sorry to bother you again. How long it takes to Fastlane catch up / detect the new release to upload it to F-Droid? I forgot to do something? AFAIK I just need to add the [txt file for the release](https://github.com/SpartanJ/ImgurViewer/blob/master/fastlane/metadata/android/en-US/changelogs/22200.txt).
Thanks in advance!

**Comment by IzzySoft** [comment]
Fastlane doesn't do the detection, it's rather F-Droid's CheckUpdates. And that looks for new releases/tags, not for changes in Fastlane. So once a new release has been tagged, that will be pulled, built and its Fastlane applied.

**Comment by SpartanJ** [comment]
Thanks for answering @IzzySoft. I already created the new release and tagged the commit. Is there any way to check if there was an issue or maybe to trigger the update manually?

**Comment by IzzySoft** [comment]
May I refer you to [my F-Droid Cheat Sheet](https://gitlab.com/-/snippets/1896503) for some useful URLs on that (and on more)? I've just checked your tag against our metadata, and it looks fine. No idea why checkupdates hasn't picked it up yet (it runs once a day, so it should have long done so). Feel free opening an issue on fdroiddata.

**Comment by IzzySoft** [comment]
Btw: Update was fetched, it was the build that failed. That's fixed as well now I've been told, so the new version should show up soon™ :smiley:

**Comment by SpartanJ** [comment]
@IzzySoft Thanks! You are always really helpful, I really appreciate it!
