### ISSUE TITLE
Open with ImgurView fails Using Google Voice

### ISSUE THREAD

**Issue by locuturus** [SpartanJ/ImgurViewer#11]
Google Voice has no built in image viewer so tapping on an image in a chat always calls external viewers.  ImgurView is listed as an option to handle GV images but the app fails to open anything.

Pixel 4a, Android 11, ImgurView 2.2.1

**Comment by SpartanJ** [comment]
Hi! I can't test it since that service it's not supported outside US. Any image link won't work? For example, an Imgur link won't work? Can you check if they are doing something nasty with the URL when you copy it?

**Comment by locuturus** [comment]
Other apps do seem to work.  If I capture the intent Google Voice sends it looks like this:

intent://com.google.android.apps.voice.fileprovider/Photo%20MMS%20images/11ba469c573e0b8f92831e304f584c60b75f0d09-14.jpg#Intent;scheme=content;type=image/jpeg;launchFlags=0x3000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://com.google.android.apps.voice.fileprovider/Photo%20MMS%20images/11ba469c573e0b8f92831e304f584c60b75f0d09-14.jpg 
MIME: image/jpeg 
URI: intent://com.google.android.apps.voice.fileprovider/Photo%20MMS%20images/11ba469c573e0b8f92831e304f584c60b75f0d09-14.jpg#Intent;scheme=content;type=image/jpeg;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

------------ 
MATCHING ACTIVITIES: 
Photos (com.google.android.apps.photos - com.google.android.apps.photos.pager.HostPhotoPagerActivity) 
Import document (com.cv.docscanner - com.cv.docscanner.activity.ShareIntentPickerImage) 
PrinterShare (com.dynamixsoftware.printershare - com.dynamixsoftware.printershare.ActivityPrintPictures) 
ImgurViewer (com.ensoft.imgurviewer - com.ensoft.imgurviewer.view.activity.ImageViewer) 
Photo Editor (com.iudesk.android.photo.editor - app.activity.PhotoViewActivity) 
Snapseed (com.niksoftware.snapseed - com.google.android.apps.snapseed.MainActivity) 
HP Print Service Plugin (com.hp.android.printservice - com.hp.android.printservice.core.SingleFileReceiver)

**Comment by SpartanJ** [comment]
I prefer not to support services that I don't have access to.
