### ISSUE TITLE
"Loaded resource is not valid" in direct Imgur link

### ISSUE THREAD

**Issue by eNV25** [SpartanJ/ImgurViewer#12]
Imgur started redirecting direct links to the proper page (eg. from `https://i.imgur.com/uSK28O9.jpg` to `https://m.imgur.com/uSK28O9`).

But when opening a direct link from app ImgurViewer gets "Loaded resource is not a valid image" error. 

You should note that the link opens in firefox first then in Imgur viewer.

![Screenshot_20201010_092632_com ensoft imgurviewer](https://user-images.githubusercontent.com/61089994/95645233-c473be00-0ada-11eb-9919-167a3aafb419.jpg)
![Screenshot_20201010_092619_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/61089994/95645235-ca699f00-0ada-11eb-9036-85016959c773.jpg)

**Comment by eNV25** [comment]
The all urls work fine if you remove `.jpg`.

**Comment by SpartanJ** [comment]
I cannot reproduce it. Both links open in ImgurViewer without any issues. It seems that the issue is on the opener app. So you're using the native Imgur app and trying to open de links with ImgurViewer?

**Comment by eNV25** [comment]
Sorry i didn't see this.

I am using opening the link from reddit using firefox as my default browser. So all in-app links open in firefox instead of chrome. In firefox I enabled the setting to "open links on app".

Can you try that?

**Comment by eNV25** [comment]
Does this issue still apply? Its been long time since I opened this.
