### ISSUE TITLE
[feature request] Reddit gallery support

### ISSUE THREAD

**Issue by 07416** [SpartanJ/ImgurViewer#13]
example gallery: https://www.reddit.com/gallery/jva359

**Comment by SpartanJ** [comment]
It's already supported. That link opens just fine with the latest version of ImgurViewer.
![2020-11-17](https://user-images.githubusercontent.com/650416/99427442-30b8bd00-28e4-11eb-9ad3-f9524c584bda.jpg)

Make sure you have the latest version of the app.
