### ISSUE TITLE
The app doesn't entirely follow dark theme

### ISSUE THREAD

**Issue by 07416** [SpartanJ/ImgurViewer#16]
The introduction image is overly bright (of Whatsapp without dark theme, seems to always be reshown when the app is closed) and the near-fullscreen white smiley could be adjusted color-wise.

**Comment by SpartanJ** [comment]
Isn't kinda irrelevant? I would prefer to use that time to improve other things. Feel free to contribute some new screenshots if you want me to change the tutorial. For the smiley face, I could use some grey color.

**Comment by user-1-2-3-4-5** [comment]
ImgurViewer doesn't currently appear to support `imgur.com/gallery/` URLs, but otherwise the image is as illustrative as can be, more or less.

Imgur hasn't supported direct links for years and creating a 'gallery' with just single picture has been possible for at least a decade.
