### ISSUE TITLE
Images loaded from Google Hangouts Chat sometimes fail

### ISSUE THREAD

**Issue by Fry-kun** [SpartanJ/ImgurViewer#17]
Image opens in Firefox
Link format: https://lh3.googleusercontent.com/foo123/bar234/baz345/deadbeef123456/s0/2021-01-15.jpg

Error in imgurViewer is a toast saying "onFailureImpl"

**Comment by Fry-kun** [comment]
There seems to be a difference between fresh & old images. Recently shared images seem to fail very often, and older ones [sometimes?] load fine in imgurViewer

**Comment by SpartanJ** [comment]
This seems to be an issue with permission to open the links. I'm not using Google Hangouts since some time ago, so I was never able to reproduce this issue. I'm not sure I can fix it.

**Comment by SpartanJ** [comment]
(I know I'm answering this issue super late, but better late than never)
Can you share another example link to test the issue? Thanks.

**Comment by SpartanJ** [comment]
Hangouts doesn't exists anymore.
