### ISSUE TITLE
Instagram: Couldn't resolve image url

### ISSUE THREAD

**Issue by teohhanhui** [SpartanJ/ImgurViewer#23]
It's a video: https://www.instagram.com/reel/CQ6KqYFJ1An/?utm_medium=copy_link

Pasting the above link into ImgurViwer gives:
`Couldn't resolve image url.`

**Comment by SpartanJ** [comment]
Thanks, I think I'll remove the Instagram support, their API is not very friendly for external applications, and I'm not very fond of the Instagram platform or any Facebook product. My idea supporting IG was to avoid using the native app, but they restrict the access so much that I'm not sure if the effort is worth it. I'll think a little bit more what to do with this.

**Comment by teohhanhui** [comment]
It works for some videos though, e.g. https://www.instagram.com/p/CReQXnNjGDN/?utm_medium=copy_link

**Comment by SpartanJ** [comment]
Closing this issue since I won't support Instagram in the near future (sorry).
