### ISSUE TITLE
Issue with imgur.com/r links

### ISSUE THREAD

**Issue by yephny** [SpartanJ/ImgurViewer#28]
I don't know what the hell these are (for subreddits, possibly) or why Imgur would need a link for something other than single images and albums, but the app does not seem to be supporting `imgur.com/r` links. For example, [https://imgur.com/r/SteamVR/G8uyWrh](https://imgur.com/r/SteamVR/G8uyWrh) will not be displayed correctly if opened with ImgurViewer. However, it still is an album and the link works if you delete the part that comes right after `/r` and replace `r` with `a` so that it becomes `imgur.com/a/G8uyWrh`

**Comment by yephny** [comment]
It still doesn't work in the new version.

**Comment by SpartanJ** [comment]
I did not fix this issue yet. Kinda forgot about it. I'll fix it soon.

**Comment by yephny** [comment]
Still doesn't work.

**Comment by SpartanJ** [comment]
Fixed in [2.3.2](https://github.com/SpartanJ/ImgurViewer/releases/tag/2.3.2).
