### ISSUE TITLE
imgur.io links

### ISSUE THREAD

**Issue by yephny** [SpartanJ/ImgurViewer#37]
The app does not work with imgur.io links, which are identical to imgur.com, though they do not redirect. Please add support for imgur.io links.

v.2.3.0.

**Comment by SpartanJ** [comment]
Will do, soon, as soon as I have some free time.

**Comment by SpartanJ** [comment]
Fixed in [2.3.2](https://github.com/SpartanJ/ImgurViewer/releases/tag/2.3.2).
