### ISSUE TITLE
Tapping on seek bar remutes the video

### ISSUE THREAD

**Issue by Borkley** [SpartanJ/ImgurViewer#42]
Every time you tap on the seek bar the video is remuted.

**Comment by SpartanJ** [comment]
Thanks for reporting it. Fixed at https://github.com/SpartanJ/ImgurViewer/commit/64153777b578dd14648d06c949e6bd8656ae62ce
A new version has been published [here](https://github.com/SpartanJ/ImgurViewer/releases/tag/2.3.3).
