### ISSUE TITLE
"com.android.volley.AuthFailureError" when opening giphy links

### ISSUE THREAD

**Issue by Waa11a** [SpartanJ/ImgurViewer#45]
example
browsing reddit from infinity 
click a giphy link from the comments
get this message and it keeps loading 
 F-droid version

**Comment by Waa11a** [comment]
screenshot
![Uploading IMG_20221022_055012.jpg…]()

**Comment by Waa11a** [comment]
screenshot
![IMG_20221022_055012](https://user-images.githubusercontent.com/89239945/197317971-09dbb13c-712e-43cf-89a9-48833c269e8b.jpg)

**Comment by SpartanJ** [comment]
@Waa11a can you please some of the links that are failing for you?

**Comment by SpartanJ** [comment]
Oh, Giphy banned ImgurViewer... ha!

**Comment by Waa11a** [comment]
> @Waa11a can you please some of the links that are failing for you?

this one "https://giphy.com/gifs/football-conference-paradi-Y5IZDZKRVIpcA"

i actually tried some other links like this one "https://i.giphy.com/media/Zy7s96dP38MlQe3OjG/giphy.mp4"
and its working
