### ISSUE TITLE
Proxy settings are ignored

### ISSUE THREAD

**Issue by licaon-kter** [SpartanJ/ImgurViewer#47]
2.3.3 F-Droid

Set proxy, eg. 127.0.0.1 port 8118 _(autotompleted? So the app developer kinda expected Orbot HTTP here?)_

Open URL, error toast can't connect

Look in the [firewall logs](https://f-droid.org/packages/eu.faircode.netguard/) to see that the app is trying _(and failing since it's blocked by default)_ to connect **directly** to the internet _bypassing_ the proxy settings.

**Comment by SpartanJ** [comment]
Yes, the proxy is only honored for images, videos won't work since the library we are using does not support proxy configuration, sadly I can't fix it. You'll have to use a global proxy setting or a VPN.

**Comment by licaon-kter** [comment]
Ceci ne pas une ~~pipe~~ video: https://i.imgur.com/cIGwlfc.jpg right?
