### ISSUE TITLE
Catbox.moe Files Not Working

### ISSUE THREAD

**Issue by OkyDooky** [SpartanJ/ImgurViewer#49]
I made some examples to test.
Image: https://files.catbox.moe/2on9pz.jpg
Movie: https://files.catbox.moe/p2yv8z.mp4
The option to open the links in ImgurViewer is there, but the image links generate a complex error in the toast message and the video links say "video reproduction failed."

**Comment by SpartanJ** [comment]
You're right, there's something wrong in the validation. I'll fix it soon. Thanks for reporting it.

**Comment by OkyDooky** [comment]
No problem. And thanks for this app. It's been extremely useful!
