### ISSUE TITLE
Version 2.3.5 doesn't play local video files

### ISSUE THREAD

**Issue by McLeree** [SpartanJ/ImgurViewer#56]
Version 2.3.5 from F-Droid
Android 8.1

When opening any local video file ImgurViewer shows black screen with error toast: `Sorry, video reproduction failed.`

Tested with .mp4 and .webm files.
Local images (.jpg, .png, and animated .gif) open as intended. 
Versions 2.3.4 and earlier open local files without problems.

**Comment by SpartanJ** [comment]
Thanks for reporting it. I'll check it out.
