### ISSUE TITLE
android 13 needs new local permissions

### ISSUE THREAD

**Issue by AeliusSaionji** [SpartanJ/ImgurViewer#58]
![Screenshot_20230110-154139](https://user-images.githubusercontent.com/4342746/211658032-e1072533-cf1e-40b5-b398-00c703ffe307.png)

sorry I don't know more about this

**Comment by SpartanJ** [comment]
Android is a nightmare. Thanks for reporting it. Do you remember what kind of content you were opening? Thanks

**Comment by AeliusSaionji** [comment]
Just opening an image from the Download folder. Here's a log, not sure if it's useful. I may have filtered too much out

[logcat_01-11-2023_23-47-35.txt.txt](https://github.com/SpartanJ/ImgurViewer/files/10398295/logcat_01-11-2023_23-47-35.txt.txt)

**Comment by SpartanJ** [comment]
This is related to issue #68 . I just pushed a fix, it seems to work.
