### ISSUE TITLE
Can't download images at all

### ISSUE THREAD

**Issue by devlman127** [SpartanJ/ImgurViewer#68]
I can view images just fine, but I'm unable to download anything as it says I lack the required permissions. I can download just fine with other apps, and I don't see a download files permission anywhere.

**Comment by SpartanJ** [comment]
Are you using Android 13, right?

**Comment by devlman127** [comment]
Yup
Saw you had issues with android 13 in the issues tab but mine was working fine before I reinstalled it, maybe because I first installed this while still in android 12

**Comment by OkyDooky** [comment]
Same issue here. LineageOS 20 (Android 13). I think Android might have removed permissions because I hadn't used the app in a while, but I see no way to restore them.

**Comment by brian6932** [comment]
Android 12 and above (SDK 30) no longer accepts `requestLegacyExternalStorage`, it requires scoped storage, so ImgurViewer for example would have to set a dir for `WRITE_EXTERNAL_STORAGE`

**Comment by OkyDooky** [comment]
Thanks for being right on top of it! It seems to be fixed on my end.
