### ISSUE TITLE
[Question] Is there any specific reason why R8/Minify is disabled in release builds?

### ISSUE THREAD

**Issue by starry-shivam** [SpartanJ/ImgurViewer#79]
Hi, I've been using a self-compiled build of this app for some time (until a new release is published), and I noticed that R8 was disabled in the release builds. So, [I recently enabled it](https://github.com/starry-shivam/ImgurViewer/blob/841567638b4f0989f6287ed2a53179a66e61ec76/app/build.gradle#L22) and built it again with minify mode. All I had to do was [add some rules](https://github.com/starry-shivam/ImgurViewer/blob/841567638b4f0989f6287ed2a53179a66e61ec76/app/proguard-rules.pro#L22) related to `EventBus` to prevent one crash when `onResume()` is called, as R8 strips/obfuscates the subscriber methods for some reason. Other than that, it's been working fine. I've also added a rule to [preserve model classes](https://github.com/starry-shivam/ImgurViewer/blob/841567638b4f0989f6287ed2a53179a66e61ec76/app/proguard-rules.pro#L20) just to be safe, as R8 sometimes causes problems with them, although it was working fine even without it (at least for Imgur URLs).

I wanted to ask if there are any other reasons you decided not to enable R8 in your release builds. One clear benefit of having R8 on is a much-optimized APK size. For example, R8-enabled builds usually have 50 to 70% reduced APK size as they don't contain many unused/unreferenced parts of the dependencies used by the app.

If you don't mind, can I create a PR with [these changes](https://github.com/starry-shivam/ImgurViewer/commit/841567638b4f0989f6287ed2a53179a66e61ec76)?

**Comment by SpartanJ** [comment]
> I wanted to ask if there are any other reasons you decided not to enable R8 in your release builds.

Depends, laziness is a good reason? :laughing: I skipped the minification exactly because of the issues you mentioned, it's no always easy to know what's going to fail, so better safe than sorry.

> One clear benefit of having R8 on is a much-optimized APK size. For example, R8-enabled builds have a 50% reduced APK size as they don't contain many unused/unreferenced parts of the dependencies used by the app.

Yes, I know, but we are talking about an 8MB application, so I honestly did not care at all.

> If you don't mind, can I create a PR with [these changes](https://github.com/starry-shivam/ImgurViewer/commit/841567638b4f0989f6287ed2a53179a66e61ec76)?

Sure! If someone already took the time we should enjoy the benefits. :smile: 

Thanks!

**Comment by starry-shivam** [comment]
Closing as completed, thanks :)

**Comment by SpartanJ** [comment]
Thanks, I'll try to prepare a new release this weekend, I forgot about it the last one.

**Comment by starry-shivam** [comment]
> Thanks, I'll try to prepare a new release this weekend, I forgot about it the last one.

Great 👌
