### ISSUE TITLE
Instagram videos not loading

### ISSUE THREAD

**Issue by jujar** [SpartanJ/ImgurViewer#82]
Opening an Instagram video link only opens the video thumbnail but the video itself doesn't load. I can also reproduce this on emulator.

ImgurViewer version 2.4.0

Oneplus 7 Pro
Android 13
DivestOS version 20-20240513-dos-guacamole
Kernel 4.14.180-dos.p666+

**Comment by SpartanJ** [comment]
If i remember correctly this is basically because it's not possible to web-scrap the video resource location so there is no fix.

**Comment by jujar** [comment]
Roger that, thank you.  I was trying to search for closed issues on this, didn't find anything similar.
